spring:
  datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@192.168.1.2:1522:orcl
        username: system
        password: 125802Aa
  jpa:
    hibernate:
       ddl-auto: update
       show-sql: true